#! /bin/sh

pgrep -x sxhkd > /del/null || sxhkd &
polybar main  
#set_lemonbar.sh --sleep-time 0.5 -c get_mpc_info #| lemonbar -p -g x30+0+30  -B "#DE6FFF" -F "#333333"
picom &
wal -i ~/Pictures/wp10.jpg



bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10
bspc config pointer_modifier    mod1
bspc config pointer_action1 move

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop
='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#pywal

# source the colors.
. "${HOME}/.cache/wal/colors.sh"
 
# Set the border colors.
bspc config normal_border_color "$color3"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

echo 
